main.obj
qtusd.js_plugin_import.obj
-LE:/DEV_PROJECTS/GIT/HdFilament/USD/Release/release/lib
-lusd_m
-lusd_ms
C:/Qt/qtWasmRelease/lib/objects-Release/QWasmIntegrationPlugin_resources_1/.rcc/qrc_wasmfonts.cpp.o
C:/Qt/qtWasmRelease/lib/objects-Release/Gui_resources_1/.rcc/qrc_qpdf.cpp.o
C:/Qt/qtWasmRelease/lib/objects-Release/Gui_resources_2/.rcc/qrc_gui_shaders.cpp.o
C:/Qt/qtWasmRelease/plugins/platforms/libqwasm.a
C:/Qt/qtWasmRelease/plugins/iconengines/libqsvgicon.a
C:/Qt/qtWasmRelease/plugins/imageformats/libqgif.a
C:/Qt/qtWasmRelease/plugins/imageformats/libqicns.a
C:/Qt/qtWasmRelease/plugins/imageformats/libqico.a
C:/Qt/qtWasmRelease/plugins/imageformats/libqjpeg.a
C:/Qt/qtWasmRelease/lib/libQt6BundledLibjpeg.a
C:/Qt/qtWasmRelease/plugins/imageformats/libqsvg.a
C:/Qt/qtWasmRelease/lib/libQt6Svg.a
C:/Qt/qtWasmRelease/plugins/imageformats/libqtga.a
C:/Qt/qtWasmRelease/plugins/imageformats/libqtiff.a
C:/Qt/qtWasmRelease/plugins/imageformats/libqwbmp.a
C:/Qt/qtWasmRelease/plugins/imageformats/libqwebp.a
C:/Qt/qtWasmRelease/lib/libQt6OpenGL.a
C:/Qt/qtWasmRelease/lib/libQt6Gui.a
C:/Qt/qtWasmRelease/lib/libQt6BundledHarfbuzz.a
C:/Qt/qtWasmRelease/lib/libQt6BundledFreetype.a
C:/Qt/qtWasmRelease/lib/libQt6BundledLibpng.a
C:/Qt/qtWasmRelease/lib/libQt6Core.a
C:/Qt/qtWasmRelease/lib/libQt6BundledZLIB.a
C:/Qt/qtWasmRelease/lib/libQt6BundledPcre2.a
-lembind
